# Generated by Django 6.0.3 on 2026-04-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('rojo', 'Reposición inmediata/Agotado'), ('amarillo', 'Pronta reposición'), ('verde', 'Producto disponible')], default='verde', max_length=15)),
            ],
            options={
                'db_table': 'extras',
            },
        ),
        migrations.CreateModel(
            name='Granel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('rojo', 'Reposición inmediata'), ('amarillo', 'Pronta reposición'), ('verde', 'Producto disponible')], default='verde', max_length=15)),
            ],
            options={
                'db_table': 'granel',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tipo',
            field=models.CharField(choices=[('platillo', 'Platillo Preparado'), ('envasado', 'Producto Envasado')], default='platillo', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='extras_asociados',
            field=models.ManyToManyField(blank=True, related_name='platillos', to='menu.extra'),
        ),
    ]
