# Generated by Django 6.0.3 on 2026-04-06 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado', models.CharField(choices=[('en_espera', 'En espera de pago'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='en_espera', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('qr', 'QR'), ('efectivo', 'Efectivo')], max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'pedido_items',
            },
        ),
    ]
